import categories from "./categoriesFake";

const dataFake = [
  {
      "id": 1,
      "name": "Three Kingdoms",
      "minPlayer": 3,
      "maxPlayer": 10,
      "bestPlayerQuantity": 8,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 30,
      "ageLimited": 12,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 0,
      "price": 31.0,
      "image": "TK.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 2,
      "name": "God git",
      "minPlayer": 2,
      "maxPlayer": 6,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 20,
      "timeToPlayTo": 30,
      "ageLimited": 14,
      "publisher": "DP games",
      "rules": "",
      "quantity": 100,
      "price": 19.0,
      "image": "EK.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 3,
      "name": "Bang",
      "minPlayer": 2,
      "maxPlayer": 10,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 40,
      "ageLimited": 11,
      "publisher": "Moste games",
      "rules": "ea",
      "quantity": 0,
      "price": 557.0,
      "image": "Bang.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 4,
      "name": "Catan",
      "minPlayer": 3,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 50,
      "timeToPlayTo": 70,
      "ageLimited": 8,
      "publisher": "TKD games",
      "rules": "Fun",
      "quantity": 6,
      "price": 19.0,
      "image": "cantan.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 5,
      "name": "Lord of waterdeep",
      "minPlayer": 2,
      "maxPlayer": 8,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 70,
      "timeToPlayTo": 100,
      "ageLimited": 12,
      "publisher": "Moste games",
      "rules": "Côl",
      "quantity": 411,
      "price": 29.0,
      "image": "Lord_of_waterdeep.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 6,
      "name": "Uno",
      "minPlayer": 2,
      "maxPlayer": 12,
      "bestPlayerQuantity": 12,
      "timeToPlayFrom": 5,
      "timeToPlayTo": 10,
      "ageLimited": 4,
      "publisher": "Moste games",
      "rules": "Fun",
      "quantity": 438,
      "price": 8.0,
      "image": "Uno.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 7,
      "name": "Blood bound",
      "minPlayer": 6,
      "maxPlayer": 12,
      "bestPlayerQuantity": 8,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 40,
      "ageLimited": 9,
      "publisher": "AVGames",
      "rules": "detroys friendship",
      "quantity": 309,
      "price": 10.0,
      "image": "Blood_bound.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 8,
      "name": "Splender",
      "minPlayer": 3,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 50,
      "timeToPlayTo": 60,
      "ageLimited": 8,
      "publisher": "Moste games",
      "rules": "be rick",
      "quantity": 421,
      "price": 19.0,
      "image": "Splendor.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 9,
      "name": "Pop up prirate",
      "minPlayer": 3,
      "maxPlayer": 10,
      "bestPlayerQuantity": 8,
      "timeToPlayFrom": 29,
      "timeToPlayTo": 30,
      "ageLimited": 5,
      "publisher": "DONGgames",
      "rules": "OKE",
      "quantity": 99,
      "price": 9.0,
      "image": "Pop-up_pirate.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 10,
      "name": "Sushi Go",
      "minPlayer": 4,
      "maxPlayer": 7,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 29,
      "timeToPlayTo": 39,
      "ageLimited": 10,
      "publisher": "TKD games",
      "rules": "EZ",
      "quantity": 199,
      "price": 4.0,
      "image": "Sushi_Go.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 12,
      "name": "Tokaido",
      "minPlayer": 4,
      "maxPlayer": 6,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 40,
      "ageLimited": 8,
      "publisher": "TKD games",
      "rules": "Chill",
      "quantity": 197,
      "price": 19.0,
      "image": "Tokaido.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 13,
      "name": "Betrayal at house in the hill",
      "minPlayer": 5,
      "maxPlayer": 8,
      "bestPlayerQuantity": 7,
      "timeToPlayFrom": 70,
      "timeToPlayTo": 100,
      "ageLimited": 12,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 100,
      "price": 55.0,
      "image": "Betrayal_at_house_on_the_Hill.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 14,
      "name": "Dead man draw",
      "minPlayer": 4,
      "maxPlayer": 5,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 30,
      "ageLimited": 9,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 45,
      "price": 5.0,
      "image": "Dead_man_draw.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 15,
      "name": "Explore Kittens",
      "minPlayer": 2,
      "maxPlayer": 9,
      "bestPlayerQuantity": 7,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 50,
      "ageLimited": 8,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 300,
      "price": 4.0,
      "image": "EK.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 16,
      "name": "Game of throne",
      "minPlayer": 4,
      "maxPlayer": 6,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 150,
      "timeToPlayTo": 160,
      "ageLimited": 15,
      "publisher": "AVGames",
      "rules": "",
      "quantity": 28,
      "price": 89.0,
      "image": "Game_of_throne.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 17,
      "name": "Love craft letter",
      "minPlayer": 3,
      "maxPlayer": 7,
      "bestPlayerQuantity": 67,
      "timeToPlayFrom": 40,
      "timeToPlayTo": 50,
      "ageLimited": 12,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 30,
      "price": 49.0,
      "image": "Love_craft_letter.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 18,
      "name": "Monopoly",
      "minPlayer": 2,
      "maxPlayer": 6,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 100,
      "timeToPlayTo": 120,
      "ageLimited": 8,
      "publisher": "Moste games",
      "rules": "",
      "quantity": 69,
      "price": 29.0,
      "image": "Monopoly.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 19,
      "name": "Peguin trap",
      "minPlayer": 2,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 15,
      "timeToPlayTo": 20,
      "ageLimited": 3,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 100,
      "price": 6.0,
      "image": "Penguin_Trap.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 20,
      "name": "Scythe",
      "minPlayer": 4,
      "maxPlayer": 6,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 80,
      "timeToPlayTo": 90,
      "ageLimited": 8,
      "publisher": "DP games",
      "rules": "",
      "quantity": 20,
      "price": 59.0,
      "image": "Scythe.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 21,
      "name": "Shadow hunter",
      "minPlayer": 4,
      "maxPlayer": 10,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 35,
      "ageLimited": 8,
      "publisher": "DP games",
      "rules": "",
      "quantity": 40,
      "price": 8.0,
      "image": "Shadow_hunter.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 22,
      "name": "Sheriff",
      "minPlayer": 3,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 40,
      "timeToPlayTo": 50,
      "ageLimited": 11,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 49,
      "price": 29.0,
      "image": "Sheriff.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 23,
      "name": "Stone age",
      "minPlayer": 3,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 50,
      "timeToPlayTo": 60,
      "ageLimited": 9,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 40,
      "price": 25.0,
      "image": "Stone_age.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 24,
      "name": "The walking dead",
      "minPlayer": 4,
      "maxPlayer": 5,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 70,
      "timeToPlayTo": 80,
      "ageLimited": 13,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 27,
      "price": 52.0,
      "image": "The_walking_dead.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 25,
      "name": "Werewolf Atifact",
      "minPlayer": 6,
      "maxPlayer": 20,
      "bestPlayerQuantity": 12,
      "timeToPlayFrom": 20,
      "timeToPlayTo": 50,
      "ageLimited": 4,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 100,
      "price": 11.0,
      "image": "WW.webp",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 26,
      "name": "Carcassonne",
      "minPlayer": 2,
      "maxPlayer": 10,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 40,
      "ageLimited": 3,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 100,
      "price": 12.0,
      "image": "Carcassonne.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 27,
      "name": "Cards Against Humanity",
      "minPlayer": 4,
      "maxPlayer": 9,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 40,
      "ageLimited": 4,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 423,
      "price": 12.0,
      "image": "Cards_Against_Humanity.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 28,
      "name": "Clue",
      "minPlayer": 4,
      "maxPlayer": 12,
      "bestPlayerQuantity": 9,
      "timeToPlayFrom": 35,
      "timeToPlayTo": 45,
      "ageLimited": 4,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 100,
      "price": 7.0,
      "image": "Clue.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 29,
      "name": "Halli Galli",
      "minPlayer": 2,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 10,
      "timeToPlayTo": 20,
      "ageLimited": 3,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 100,
      "price": 4.0,
      "image": "Halli_Galli.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 30,
      "name": "What do you meme",
      "minPlayer": 2,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 15,
      "timeToPlayTo": 20,
      "ageLimited": 4,
      "publisher": "AVGame",
      "rules": "",
      "quantity": 50,
      "price": 3.0,
      "image": "What_do_you_meme.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 31,
      "name": "Watch Ya' Mouth",
      "minPlayer": 4,
      "maxPlayer": 8,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 20,
      "timeToPlayTo": 30,
      "ageLimited": 8,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 90,
      "price": 17.0,
      "image": "Watch_Ya'_Mouth.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 32,
      "name": "Trouble DreamWorks Trolls World Tour Edition",
      "minPlayer": 4,
      "maxPlayer": 5,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 30,
      "ageLimited": 9,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 43,
      "price": 5.0,
      "image": "Trouble_DreamWorks_Trolls_World_Tour_Edition.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 33,
      "name": "Ticket To Ride",
      "minPlayer": 2,
      "maxPlayer": 9,
      "bestPlayerQuantity": 7,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 50,
      "ageLimited": 8,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 297,
      "price": 4.0,
      "image": "Ticket_To_Ride.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 34,
      "name": "Throw Throw Burrito",
      "minPlayer": 4,
      "maxPlayer": 6,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 150,
      "timeToPlayTo": 160,
      "ageLimited": 15,
      "publisher": "AVGames",
      "rules": "",
      "quantity": 27,
      "price": 89.0,
      "image": "Throw_Throw_Burrito.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 35,
      "name": "Smart Ass",
      "minPlayer": 3,
      "maxPlayer": 7,
      "bestPlayerQuantity": 67,
      "timeToPlayFrom": 40,
      "timeToPlayTo": 50,
      "ageLimited": 12,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 30,
      "price": 49.0,
      "image": "Smart_Ass.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 36,
      "name": "SKIP BO",
      "minPlayer": 2,
      "maxPlayer": 6,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 100,
      "timeToPlayTo": 120,
      "ageLimited": 8,
      "publisher": "Moste games",
      "rules": "",
      "quantity": 69,
      "price": 29.0,
      "image": "SKIP_BO.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 37,
      "name": "Scrabble Junior",
      "minPlayer": 2,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 15,
      "timeToPlayTo": 20,
      "ageLimited": 3,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 99,
      "price": 6.0,
      "image": "Scrabble_Junior.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 38,
      "name": "Ravensburger Labyrinth",
      "minPlayer": 4,
      "maxPlayer": 6,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 80,
      "timeToPlayTo": 90,
      "ageLimited": 8,
      "publisher": "DP games",
      "rules": "",
      "quantity": 20,
      "price": 59.0,
      "image": "Ravensburger_Labyrinth.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 39,
      "name": "Photosynthesis",
      "minPlayer": 4,
      "maxPlayer": 10,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 35,
      "ageLimited": 8,
      "publisher": "DP games",
      "rules": "",
      "quantity": 40,
      "price": 8.0,
      "image": "Photosynthesis.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 40,
      "name": "Pandemic",
      "minPlayer": 3,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 40,
      "timeToPlayTo": 50,
      "ageLimited": 11,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 50,
      "price": 29.0,
      "image": "Pandemic.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 41,
      "name": "monpoly origional",
      "minPlayer": 3,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 50,
      "timeToPlayTo": 60,
      "ageLimited": 9,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 40,
      "price": 25.0,
      "image": "monpoly_origional.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 42,
      "name": "Monopoly Socialism",
      "minPlayer": 4,
      "maxPlayer": 5,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 70,
      "timeToPlayTo": 80,
      "ageLimited": 13,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 30,
      "price": 52.0,
      "image": "Monopoly_Socialism.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 43,
      "name": "Monopoly Game of Thrones",
      "minPlayer": 6,
      "maxPlayer": 20,
      "bestPlayerQuantity": 12,
      "timeToPlayFrom": 20,
      "timeToPlayTo": 50,
      "ageLimited": 4,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 100,
      "price": 11.0,
      "image": "Monopoly_Game_of_Thrones.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 44,
      "name": "Mindware Qwirkle",
      "minPlayer": 2,
      "maxPlayer": 10,
      "bestPlayerQuantity": 5,
      "timeToPlayFrom": 30,
      "timeToPlayTo": 40,
      "ageLimited": 3,
      "publisher": "DONGgames",
      "rules": "",
      "quantity": 100,
      "price": 12.0,
      "image": "Mindware_Qwirkle.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 45,
      "name": "king_domino",
      "minPlayer": 4,
      "maxPlayer": 9,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 25,
      "timeToPlayTo": 40,
      "ageLimited": 4,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 422,
      "price": 12.0,
      "image": "king_domino.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 46,
      "name": "Jax Sequence",
      "minPlayer": 4,
      "maxPlayer": 12,
      "bestPlayerQuantity": 9,
      "timeToPlayFrom": 35,
      "timeToPlayTo": 45,
      "ageLimited": 4,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 100,
      "price": 7.0,
      "image": "Jax_Sequence.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 47,
      "name": "It’s in The Bag!",
      "minPlayer": 2,
      "maxPlayer": 5,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 10,
      "timeToPlayTo": 20,
      "ageLimited": 3,
      "publisher": "YOGA games",
      "rules": "",
      "quantity": 100,
      "price": 4.0,
      "image": "It_is_in_The_Bag.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 48,
      "name": "Hasbro Risk",
      "minPlayer": 2,
      "maxPlayer": 4,
      "bestPlayerQuantity": 4,
      "timeToPlayFrom": 15,
      "timeToPlayTo": 20,
      "ageLimited": 4,
      "publisher": "AVGame",
      "rules": "",
      "quantity": 50,
      "price": 3.0,
      "image": "Hasbro_Risk.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  },
  {
      "id": 49,
      "name": "Hasbro Connect 4",
      "minPlayer": 4,
      "maxPlayer": 8,
      "bestPlayerQuantity": 6,
      "timeToPlayFrom": 20,
      "timeToPlayTo": 30,
      "ageLimited": 8,
      "publisher": "TKD games",
      "rules": "",
      "quantity": 90,
      "price": 17.0,
      "image": "Hasbro_Connect_4.png",
      "status": null,
      "categories": [categories[0], categories[3]],
  }
];
export default dataFake;
